### ISSUE TITLE
LSP doesn't support advanced function types

### ISSUE THREAD

**Issue by Baileyeatspizza** [NightrainsRbx/RobloxLsp#140] opened 2022-01-13 18:20 UTC
My issue is basically this
https://user-images.githubusercontent.com/68239467/149386398-858dbd36-41ca-46b7-9043-572727683208.mov
<img width="562" alt="Screenshot 2022-01-13 at 18 18 07" src="https://user-images.githubusercontent.com/68239467/149386695-ee6aecfd-149d-44f8-8997-2502ee4390ab.png">
that is valid code in Roblox Studio

But in Roblox LSP I get these errors
<img width="787" alt="Screenshot 2022-01-13 at 18 17 40" src="https://user-images.githubusercontent.com/68239467/149386601-4a307207-164b-44b9-b7aa-94d3e1a13e2c.png">

Roblox LSP just doesn't think the function has been defined due to the typechecking

**Comment by NightrainsRbx** [comment] 2022-01-13 18:34
This is generic type packs. duplicate of #129

**Closed by NightrainsRbx** 2022-01-13 18:34 UTC
